config/routes.rb
Catornotcat::Application.routes.draw do
  resources :cats

  root :to => 'cats#index'

end

app/models/cat.rb
class Cat < ActiveRecord::Base
  attr_accessible :picture
  has_attached_file :picture, :styles => { :medium => "300x300>", :thumb => "100x100>" }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
    @cats = Cat.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cats }
    end
  end
  
  # GET /cats/1
  # GET /catss/1.json
  def show
    @cat = Cat.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @cat }
    end
  end

  # GET /cats/new
  # GET /cats/new.json
  def new
    @cat = Cat.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cat }
    end
  end

  # GET /cat/1/edit
  def edit
    @cat = Cat.find(params[:id])
  end  

  #def create
  #  @cat = Cat.create( params[:cat] )
  #end
  
  # POST /cats
  # POST /cats.json
  def create
    @cat = Cat.new(params[:cat])

    respond_to do |format|
      if @cat.save
        format.html { redirect_to @cat, notice: 'Cat was successfully created.' }
        format.json { render json: @cat, status: :created, cat: @cat }
      else
        format.html { render action: "new" }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cats/1
  # PUT /cats/1.json
  def update
    @cat = Cat.find(params[:id])

    respond_to do |format|
      if @cat.update_attributes(params[:cat])
        format.html { redirect_to @cat, notice: 'Cat was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cats/1
  # DELETE /cats/1.json
  def destroy
    @cat = Cat.find(params[:id])
    @cat.destroy

    respond_to do |format|
      format.html { redirect_to cat_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cats/_form.html.erb
<%= form_for @cat, :url => cats_path, :html => { :multipart => true } do |f| %>
  <% if @cat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cat.errors.count, "error") %> prohibited this cat from being saved:</h2>

      <ul>
      <% @cat.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :picture, :class => 'control-label' %>
    <div class="controls">
      <%= f.file_field :picture, :class => 'file_field' %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cats/index.html.erb
Cat or Not Cat? <%= link_to 'new cat', new_cat_path %>
<p>
<% @cats.each do |cat| %>
	<%= link_to image_tag(cat.picture.url(:thumb)), cat_path(cat) %><br />
<% end %>
</p>

app/views/cats/new.html.erb
<h1>New cat</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/cats/show.html.erb
<%= image_tag @cat.picture.url(:medium) %>
<p>
	Cat or Not Cat?
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Catornotcat</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>